apiVersion: v1
kind: Service
metadata:
  name: service-service-one
  labels:
    app: service-one
spec:
  type: ClusterIP
  ports:
    - port: 5678
      name: "http"
      targetPort: 5678
  selector:
    app: service-one
